# Undervisning

Under beskrives undervisningen i STV2022. 

## Forelesninger

Kurset har 10 forelesninger:

1.  [Intro!](#introduksjon) (uke 34)
2.  [Anskaffelse](#anskaff) og [innlasting av tekst](#lastetekst)  (uke 35)
3.  [Forbehandling av tekst 1](#prepros) (uke 36)
4.  [Forbehandling av tekst 2](#prepros) (uke 37)
5.  [Bruke API](#anskaff) (Stortinget) (uke 38)
6.  [Veiledet](#sup) versus [ikke-veiledet](#unsup) læring (uke 41)
7.  [Ordbøker](#ordboker), [tekstlikhet](#tekststats) og [sentiment](#sentiment) (uke 42)
8.  Klassifisering av tekst -- [temamodellering](#topicmod) (uke 43)
9.  [Estimere latent posisjon fra tekst](#posisjon) (uke 44)
10. [Oppsummering](oppsummering)! (uke 46)

Det er sterkt anbefalt at man ser over pensum før forelesning og seminar.

## Pensum

### Generelt

Under er en liste over bidrag som vil bli dekket kontinuerlig gjennom hele kurset:

1. @Silge2017
2. @Grimmer2022
3. @Benoit2017
2. @Jurafsky2021b (anbefalt)
4. @Wickham2016 (anbefalt)

### Uke 34. Introduksjon (Solveig og Martin)

Den første uken vil vi fokusere på de genrelle konseptene innenfor kvantitativ tekstanalyse, prosessen med å gå fra rå tekst til slutningsanalyse, potensielle fallgruver, med mer. 

1. @Grimmer2022 kap. 1-2 og 22 (36 sider)
2. @Lucas2015 (24 sider)
3. @Silge2017 kap. 1 (9 sider)
4. @Pang2008 kap. 1 (10 sider)

### Uke 35. Anskaffelse og innlasting av tekst (Martin)

1. @Grimmer2022 kap. 3-4 (14 sider)
1. @Cooksey2014 kap. 1 (4 sider)
2. @Wickham2020 (8 sider)
3. @Hoyland2019 (22 sider)

### Uke 36. Forbehandling av tekst 1 (Martin)

1. @Grimmer2022 kap. 5 (11 sider)
1. @Silge2017 kap. 3 (9 sider)
3. @Joergensen2019 (10 sider)
4. @Barnes2019 (12 sider)
5. @Benoit2020 (11 sider)

**Seminar 1: Anskaffe tekst og lage dtm i R**

### Uke 37. Forbehandling av tekst 2 (Solveig)

1. @Grimmer2022 kap. 9 (7 sider)
1. @Silge2017 kap. 4 (15 sider)
3. @Denny2018 (21 sider)

### Uke 38. Bruke API -- Case: Stortinget (Martin)

1. @datastortinget2022 (1 sider)
2. @Soeyland2022 (1 sider)
3. @Finseraas2021 (10 sider)

**Seminar 2: Preprosessering av tekstdata i R**

### Uke 39. INGEN UNDERVISNING

### Uke 40. INGEN UNDERVISNING

### Uke 41. Veiledet læring og ikke-veiledet læring (Solveig)

1. @Grimmer2022 kap. 10 og 17 (24 sider)
1. @dorazio_separating_2014 (18 sider)
2. @feldman_sanger_20061 (17 sider)
3. @feldman_sanger_20062 (11 sider)
4. @muchlinski_siroky_he_kocher_2016 (16 sider)

### Uke 42. Ordbøker, tekstlikhet og sentiment (Solveig)

1. @Grimmer2022 kap. 7 og 16 (12 sider)
1. @Silge2017 kap. 2 (11 sider)
2. @Pang2008 kap. 3-4 (26 sider)
3. @liu_introduction_2015 (15 sider)
4. @liu_problem_2015 (30 sider)

**Seminar 3: Sup vs. unsup i R**

### Uke 43. Klassifisering av tekst -- Temamodellering (Martin)

1. @Grimmer2022 kap. 13 og  (13 sider)
1. @Blei2012 (8 sider)
2. @Silge2017 kap. 6 (14 sider)
3. @Roberts2014 (19 sider)

### Uke 44. Estimere latent posisjon fra tekst (Solveig)

1. @Laver2003 (20 sider)
2. @Slapin2008 (18 sider)
3. @Lowe2017 (15 sider)
4. @Lauderdale2016 (20 sider)
3. @Peterson2018 (8 sider)

**Seminar 4: Modelleringsmetoder i R**

### Uke 46. Oppsummering (Solveig og Martin)

1. @Grimmer2022 kap 28 (5 sider)
1. @Wilkerson2017 (19 sider)

**Seminar 5: Fra tekst til funn -- Q&A/Oppg.hjelp**


## Seminarer

Seminarene vil bli

## Nyttige ressurser

- [Arbeidsbøker for R ved UiO](https://shinyibv02.uio.no/connect/#/apps/55/access)
- [R materiale for STV1020](https://github.com/liserodland/STV1020)


