---
title: "Pensum STV2022"
author: 
  - Eli Sofie Baltzersen^[e.s.baltzersen@stv.uio.no]
  - Martin Søyland^[martin.soyland@stv.uio.no]
date: '`r format(Sys.time(), "%d-%m-%Y")`'
output: pdf_document
bibliography: ../../referanser/stv2022.bib
editor_options: 
  chunk_output_type: console
---

# Generelt

Under er en liste over bidrag som vil bli dekket kontinuerlig gjennom hele kurset:

1. @Silge2017
2. @Grimmer2022
3. @Benoit2017
2. @Jurafsky2021b (anbefalt)
4. @Wickham2016 (anbefalt)

# Uke 34. Introduksjon (Eli og Martin)

1. @Grimmer2022 kap. 1-2 og 22 
2. @Lucas2015 
3. @Silge2017 kap. 1 
4. @Pang2008 kap. 1 

# Uke 35. Anskaffelse og innlasting av tekst (Martin)

1. @Grimmer2022 kap. 3-4 
1. @Cooksey2014 kap. 1 
2. @Wickham2020 
3. @Hoyland2019 

# Uke 36. Forbehandling av tekst 1 (Martin)

1. @Grimmer2022 kap. 5 
1. @Silge2017 kap. 3 
3. @Joergensen2019 
4. @Barnes2019 
5. @Benoit2020 

Seminar 1: Anskaffe tekst og lage dtm i R

# Uke 37. Forbehandling av tekst 2 (Eli)

1. @Grimmer2022 kap. 9 
1. @Silge2017 kap. 4 
3. @Denny2018 

# Uke 38. Bruke API -- Case: Stortinget (Martin)

1. @datastortinget2022 
2. @Soeyland2022 
3. @Finseraas2021 

Seminar 2: Preprosessering av tekstdata i R

# Uke 39. INGEN UNDERVISNING

# Uke 40. INGEN UNDERVISNING

# Uke 41. Veiledet læring og ikke-veiledet læring (Eli)

1. @Grimmer2022 kap. 10 og 17 
1. @dorazio_separating_2014 
2. @feldman_sanger_20061 
3. @feldman_sanger_20062 
4. @muchlinski_siroky_he_kocher_2016 

# Uke 42. AI, maskinlæring og dyp læring (Martin)

1. @Grimmer2022 kap 19
1. @Chatsiou2020
2. @Olivella2020
3. @Ongsulee2017

# Uke 43. Ordbøker, tekstlikhet og sentiment (Eli)

1. @Grimmer2022 kap. 7 og 16 
1. @Silge2017 kap. 2 
2. @Pang2008 kap. 3-4 
3. @liu_introduction_2015 
4. @liu_problem_2015 

Seminar 3: Sup vs. unsup i R

# Uke 44. Klassifisering av tekst -- Temamodellering (Martin)

1. @Grimmer2022 kap. 13 og  
1. @Blei2012 
2. @Silge2017 kap. 6 
3. @Roberts2014 

Seminar 4: Modelleringsmetoder i R

# Uke 46. Oppsummering (Eli og Martin)

1. @Grimmer2022 kap 28 
1. @Wilkerson2017 

Seminar 5: Fra tekst til funn -- Q&A/Oppg.hjelp

# Antall sider

```{r ant_sider, echo=FALSE}
library(stringr)
hm <- readLines("./pensum.Rmd")
hm |> 
  str_extract_all("[0-9]+\\ssider") |>
  unlist() |>
  str_extract("[0-9]+") |>
  as.numeric() |>
  sum()

```


# Referanser




